### ISSUE TITLE
USER STORY: Search & Filter APIs

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#11]
As an **Admin**,

I want to **search and filter the instances of in the database**,

so that **can easily find particular instances I'm looking for**

### Acceptance Criteria

1. The browser API view has a free-text search functionality for Task and Profile
2. The browser API view has pre-defined filters for Task and Profile

### Tasks

- [x] add extra fields
  - [x] Task
  - [x] Profile
 - [x] Annotate querysets
   - [x] Task
   - [x] Profile
- [x] Filter feature to API
   - [x] Task
   - [x] Profile
- [x] Add Search feature to API
   - [x] Task
   - [x] Profile
