### ISSUE TITLE
USER STORY: Routing

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#18]
As a **Visitor**,

I want to **navigate through pages without refreshing**,

so that **I can reach the desired content more quickly**

### Acceptance Criteria

1. Nav Bar links Home, Sign Up & Sign In route user to relevant component without refreshing

### Tasks

- [x] `npm install react-router-dom@5.3.0`
- [x] add rounting for Home & Signin pages
- [x] add links to logo, Home Signin & Signup in Navbar
