### ISSUE TITLE
USER STORY: Create Projects API

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#19]
As an **Admin**,

I want to **create a Projects app in the backend**,

so that **user's projects can be handled appropriately**

### Acceptance Criteria

1. A Projects API exists in the backend with full CRUD functionalities
3. Only logged-in users can manage their own project resources

### Tasks

- [x] create `projects` app
  - [x] add `projects` app to `INSTALLED_APPS` in `settings.py`
- [x] create `Projects` model
  - [x] makemigrations
  - [x] migrate
- [x] create `projects` views
  - [x] list view
  - [x] detail view
- [x] create `projects` serializers
  - [x] list serializer
  - [x] detail serializer
 - [x] restrict `project` resource
  - [x] create `IsOwnerOrReadOnly` permission (if not created yet)
  - [x] add `is_owner` field to serializer
  - [x] adjust `project/views.py` to restrict editing a profile to the profile owner
- [x] automated tests
  - [x] test project list view
  - [x] test project detail view

#### Manual testing
- [x] project list
  - [x] list of instances visible to all users
  - [x] logged-in users can create new instance
  - [x]  visitors (not logged in) cannot create instances
- [x] project detail
  - [x] existing instance is visible to all users
  - [x] putting the wrong instance ID in the URL gives a 404 error
  - [x] logged-in users can edit their own instance
  - [x] logged-in users can delete their own instance
  - [x] logged-in users cannot edit other users' instances
  - [x] logged-in users cannot delete other users' instances
  - [x] visitors (not logged in) cannot edit instances
  - [x] visitors (not logged in) cannot delete instances
