### ISSUE TITLE
USER STORY: Create Comments API

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#20]
As an **Admin**,

I want to **create a Comments app in the backend**,

so that **user's comments can be handled appropriately**

### Acceptance Criteria

1. A Comments API exists in the backend with full CRUD functionalities
3. Only logged-in users can manage their own comment resources

### Tasks

- [x] create `comments` app
  - [x] add `comments` app to `INSTALLED_APPS` in `settings.py`
- [x] create `Comments` model
  - [x] makemigrations
  - [x] migrate
- [x] create `comments` views
  - [x] list view
  - [x] detail view
- [x] create `comments` serializers
  - [x] list serializer
  - [x] detail serializer
 - [x] restrict `comment` resource
  - [x] create `IsOwnerOrReadOnly` permission (if not created yet)
  - [x] add `is_owner` field to serializer
  - [x] adjust `comments/views.py` to restrict editing a profile to the profile owner
- [x] automated tests
  - [x] test comment list view
  - [x] test comment detail view

#### Manual testing
  - [x] list of instances visible to all users
  - [x] logged-in users can create new instance
  - [x]  visitors (not logged in) cannot create instances
  - [x] existing instance is visible to all users
  - [x] putting the wrong instance ID in the URL gives a 404 error
  - [x] logged-in users can edit their own instance
  - [x] logged-in users can delete their own instance
  - [x] logged-in users cannot edit other users' instances
  - [x] logged-in users cannot delete other users' instances
  - [x] visitors (not logged in) cannot edit instances
  - [x] visitors (not logged in) cannot delete instances
