### ISSUE TITLE
USER STORY: Set up user authentication in the API browser view

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#4]
As an **Admin**,

I want to **set up user authentication in the API**,

so that **I can enable users to sign up/in/out**

### Acceptance Criteria

1. The API handles user signup/in/out using a username and password

### Tasks

- [x] add authentication path to `api-task-manager/urls.py`: `path('api-auth/', include('rest_framework.urls')),`
- [x] enable JWT (JSON Web Token authentication in Prod)
- [x] add registration paths to `api-task-manager/urls.py`:
  ```
  path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path(
        'dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')
    ),
  ```
- [x] fix `dj-rest-auth` bug by adding custom logout route and view

**Comment by blahosyl** [comment]
[add custom logout route and view](https://github.com/blahosyl/task-manager-api/commit/d5f498fff786b7d7d639df0cf0bceb04b694fcd9)
