### ISSUE TITLE
USER STORY: Create Profiles API

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#6]
As an **Admin**,

I want to **create a Profiles app in the backend**,

so that **user's profiles can be handled appropriately**

### Acceptance Criteria

1. A Profiles API exists in the backend with full CRUD functionalities
2. A profile is automatically created for each user account
3. Only logged-in users can manage their own profile resources

### Tasks

- [x] create `profiles` app
  - [x] add `profiles` app to `INSTALLED_APPS` in `settings.py`
- [x] create `Profile` model
  - [x] makemigrations
  - [x] migrate
- [x] create `profile` views
  - [x] list view
  - [x] detail view
- [x] create `profile` serializers
  - [x] list serializer
  - [x] detail serializer
- [x] restrict `profile` resource
  - [x] create `IsOwnerOrReadOnly` permission
  - [x] add `is_owner` field to serializer
  - [x] adjust `profile/views.py` to restrict editing a profile to the profile owner
