### ISSUE TITLE
USER STORY: Create Tasks API

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#7]
As an **Admin**,

I want to **create a Tasks app in the backend**,

so that **user's tasks can be handled appropriately**

### Acceptance Criteria

1. A Tasks API exists in the backend with full CRUD functionalities
3. Only logged-in users can manage their own task resources

### Tasks

- [x] create `tasks` app
  - [x] add `tasks` app to `INSTALLED_APPS` in `settings.py`
- [x] create `Tasks` model
  - [x] makemigrations
  - [x] migrate
- [x] create `tasks` views
  - [x] list view
  - [x] detail view
- [x] create `tasks` serializers
  - [x] list serializer
  - [x] detail serializer
 - [x] restrict `task` resource
  - [x] create `IsOwnerOrReadOnly` permission (if not created yet)
  - [x] add `is_owner` field to serializer
  - [x] adjust `task/views.py` to restrict editing a profile to the profile owner
- [x] automated tests
  - [x] test task list view
  - [x] test task detail view
