### ISSUE TITLE
USER STORY: Create Watchers API

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-api#8]
As an **Admin**,

I want to **create a Watchers app in the backend**,

so that **user's watched tasks can be handled appropriately**

### Acceptance Criteria

1. A Watchers API exists in the backend with full CRUD functionalities
3. Only logged-in users can manage their own watch resources

### Tasks

- [x] create `watchers` app
  - [x] add `watchers` app to `INSTALLED_APPS` in `settings.py`
- [x] create `Watchers` model
  - [x] makemigrations
  - [x] migrate
- [x] create `watchers` views
  - [x] list view
  - [x] detail view
- [x] create `watchers` serializers
  - [x] list serializer
  - [x] detail serializer
 - [x] restrict `watchers` resource
  - [x] create `IsOwnerOrReadOnly` permission (if not created yet)
  - [x] add `is_owner` field to serializer
  - [ ] adjust `watchers/views.py` to restrict editing a profile to the profile owner

#### Manual testing
- [x] watchers list
  - [x] list of instances visible to all users
  - [x] logged-in users can create new instance
  - [x]  visitors (not logged in) cannot create instances
- [x] watchers detail
  - [x] existing instance is visible to all users
  - [x] putting the wrong instance ID in the URL gives a 404 error
  - [x] logged-in users can delete their own instance
  - [x] logged-in users cannot delete other users' instances
  - [x] visitors (not logged in) cannot delete instances

**Comment by blahosyl** [comment]
[rename `watch` app to `watchers`](https://github.com/blahosyl/task-manager-api/commit/87141b886c13865e11d88ed67a9a33a374aebdaa)

**Comment by blahosyl** [comment]
[add Watchers serializer, list & detail view, urls](https://github.com/blahosyl/task-manager-api/commit/12cef9931415ed03774955abe85311a14f9b9305)
